### ISSUE TITLE
Downloading version and changelog from the wrong host.

### ISSUE THREAD

**Issue by Seifur** [vadi2/ire-mapping-script#1]
Due to this line of mmp.checkforupdate() the mmp_downloaded_file() function still thinks the latest version is 15.3.1 and reports that version 15.5.1 is out of date.

```
downloadFile(mmp.mapperfile, "http://bazaar.launchpad.net/~mudlet-makers/mudlet/mapper-lua/download/head:/version-20110910005237-2917fpevgi4koxqk-1/version")
```

mmp.retrievechangelog() also retrieves a file from the old host.

```
downloadFile(mmp.changelogfile, "http://bazaar.launchpad.net/~mudlet-makers/mudlet/mapper-lua/files")
```

mmp_checkupdatestart() is called when the "mmp logged in" event is raised which then creates a temptimer to call mmp.checkforupdate()

**Comment by vadi2** [comment]
It's still an issue, I just released from launchpad again for the time
being.
